// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5fKB18QJX2rhGtC6yraGumJq63CM9xw',
    appId: '1:940556220087:web:788096ff1bac2d51debf32',
    messagingSenderId: '940556220087',
    projectId: 'turn-around-fa74b',
    authDomain: 'turn-around-fa74b.firebaseapp.com',
    databaseURL: 'https://turn-around-fa74b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'turn-around-fa74b.firebasestorage.app',
    measurementId: 'G-0W95QV4024',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aZIJwY9u-DtMN8Q9429NVOwUGMNI6Mk',
    appId: '1:940556220087:android:78bfa0cb05bf4e4bdebf32',
    messagingSenderId: '940556220087',
    projectId: 'turn-around-fa74b',
    databaseURL: 'https://turn-around-fa74b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'turn-around-fa74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2l2PX0gg65yPs8GxuHBPx8tZztI_izc',
    appId: '1:940556220087:ios:424968d4b7145cfadebf32',
    messagingSenderId: '940556220087',
    projectId: 'turn-around-fa74b',
    databaseURL: 'https://turn-around-fa74b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'turn-around-fa74b.firebasestorage.app',
    iosBundleId: 'com.example.restoProfCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2l2PX0gg65yPs8GxuHBPx8tZztI_izc',
    appId: '1:940556220087:ios:424968d4b7145cfadebf32',
    messagingSenderId: '940556220087',
    projectId: 'turn-around-fa74b',
    databaseURL: 'https://turn-around-fa74b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'turn-around-fa74b.firebasestorage.app',
    iosBundleId: 'com.example.restoProfCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo5fKB18QJX2rhGtC6yraGumJq63CM9xw',
    appId: '1:940556220087:web:970ff927b3866583debf32',
    messagingSenderId: '940556220087',
    projectId: 'turn-around-fa74b',
    authDomain: 'turn-around-fa74b.firebaseapp.com',
    databaseURL: 'https://turn-around-fa74b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'turn-around-fa74b.firebasestorage.app',
    measurementId: 'G-EQ7BPYX1E7',
  );
}
